server:
  port: 9000
spring:
  application:
    name: orderservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
feign:
  client:
    config:
      default: # default 全局配置
        loggerLevel: BASIC #日志级别，Basic就是基本的请求额和响应信息
  httpclient:
    enabled: true #开启feign对httpclient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
